# Generated by Django 4.0.3 on 2022-08-17 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('experience', models.TextField(blank=True, max_length=500)),
                ('b_degree', models.TextField(blank=True, max_length=10)),
                ('b_institute', models.TextField(blank=True, max_length=50)),
                ('m_degree', models.TextField(blank=True, max_length=10)),
                ('m_institute', models.TextField(blank=True, max_length=50)),
                ('phd_degree', models.TextField(blank=True, max_length=10)),
                ('phd_institute', models.TextField(blank=True, max_length=50)),
                ('sched_test', models.CharField(blank=True, max_length=50)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_kavprof',
            },
        ),
    ]
