# Generated by Django 4.0.3 on 2022-08-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='reg_id',
            new_name='user',
        ),
    ]
