# Generated by Django 4.0.3 on 2022-08-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_reg_id_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_fk',
        ),
    ]
