# Generated by Django 3.2 on 2022-09-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220902_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kav_email',
            new_name='gmail',
        ),
    ]
