# Generated by Django 3.2 on 2022-09-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_proj_scrum_project_scrum_master'),
        ('account', '0003_rename_kav_email_user_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usertype', to='dashboard.usertype'),
            preserve_default=False,
        ),
    ]
