# Generated by Django 4.0.3 on 2022-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_reg_id_userprofile_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_openings',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
