# Generated by Django 3.2 on 2022-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('marital_status', models.CharField(max_length=20)),
                ('DOB', models.DateField(max_length=20)),
                ('NIC', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=20)),
                ('passport_expiry', models.DateField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('cnic_img', models.CharField(max_length=50)),
                ('emp_photo', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('dnt', models.CharField(max_length=20)),
                ('joinig_departmeate', models.DateField(max_length=20)),
                ('leaving_date', models.DateField(max_length=20)),
                ('hiring_comments', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('kav_email', models.EmailField(max_length=20)),
                ('current_salary', models.IntegerField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('leaving_reason', models.CharField(max_length=200)),
                ('starting_salary', models.IntegerField(max_length=20)),
                ('emp_agreement_image', models.CharField(max_length=50)),
                ('offer_letter_img', models.CharField(max_length=50)),
                ('NDA_letter_img', models.BooleanField(max_length=50)),
                ('has_NDA_letter_img', models.BooleanField(default=False)),
                ('has_offer_letter_img', models.BooleanField(default=False)),
                ('has_experience_letter_img', models.BooleanField(default=False)),
                ('has_cnic_img', models.BooleanField(default=False)),
                ('has_certificate_img', models.BooleanField(default=False)),
                ('has_emp_agreement_img', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('last_modified_date', models.DateTimeField(max_length=20)),
                ('last_login', models.DateTimeField(max_length=20)),
                ('is_virtual', models.BooleanField(default=False)),
                ('residence_city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('sub_domain', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_no', models.IntegerField(max_length=5, null=True)),
                ('total_sprint', models.IntegerField(max_length=5, null=True)),
                ('tasks_assigned', models.IntegerField(max_length=5)),
                ('completed_tasks', models.IntegerField(max_length=5)),
                ('pending_tasks', models.IntegerField(max_length=5)),
                ('QA_failed', models.IntegerField()),
                ('story_points_completed', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrum', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('employee', models.BooleanField(default=False)),
                ('new_reg', models.BooleanField(default=False)),
            ],
        ),
    ]
