# Generated by Django 3.2 on 2022-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sprint_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kav_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='starting_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='completed_tasks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='pending_tasks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='tasks_assigned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='total_sprint',
            field=models.IntegerField(null=True),
        ),
    ]
