# Generated by Django 3.2 on 2022-08-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220831_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='admin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='employee',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='new_reg',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='scrum',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
