# Generated by Django 3.2 on 2022-08-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220831_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='new_reg',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='scrum',
        ),
    ]
