# Generated by Django 3.2 on 2022-08-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220831_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usertype'),
            preserve_default=False,
        ),
    ]
