# Generated by Django 3.2 on 2022-08-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_employee_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joinig_departmeate',
            new_name='joinig_department',
        ),
    ]
