# Generated by Django 3.2 on 2022-09-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_joinig_departmeate_employee_joinig_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_scrum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee'),
            preserve_default=False,
        ),
    ]
