# Generated by Django 3.2 on 2022-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='NIC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cnic_img',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dnt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_photo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hiring_comments',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joinig_department',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kav_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_modified_date',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leaving_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leaving_reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='starting_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='QA_failed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='completed_tasks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='pending_tasks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='story_points_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='tasks_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
