# Generated by Django 3.2 on 2022-09-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220901_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='has_NDA_letter_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_certificate_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_cnic_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_emp_agreement_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_experience_letter_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='has_offer_letter_img',
        ),
    ]
