# Generated by Django 3.2 on 2022-09-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_employee_nda_letter_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usertype'),
        ),
    ]
