# Generated by Django 3.2 on 2022-09-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220902_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='proj_scrum',
            new_name='scrum_master',
        ),
    ]
