# Generated by Django 3.2 on 2022-09-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_rename_proj_scrum_project_scrum_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='project',
            new_name='project_fk',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='scrum_master',
            new_name='scrum_master_fk',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='project',
            new_name='project_fk',
        ),
        migrations.CreateModel(
            name='ResourceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('resource_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
